---

services:
  jumpstart:
    build: .
    container_name: WeatherWorks Website
    ports:
      - "8000:8000"
    environment:
      - CALENDAR_URL=${CALENDAR_URL}
      - CALENDAR_OUTLOOK_DAYS=${CALENDAR_OUTLOOK_DAYS}
      - CALENDAR_EVENT_MAXIMUM=${CALENDAR_EVENT_MAXIMUM}
      - CALENDAR_TIMEZONE=${CALENDAR_TIMEZONE}

      - WATCHED_CHANNELS=${WATCHED_CHANNELS}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - SLACK_JUMPSTART_MESSAGE=${SLACK_JUMPSTART_MESSAGE}

      - WIKI_API=${WIKI_API}
      - WIKIBOT_USER=${WIKIBOT_USER}
      - WIKIBOT_PASSWORD=${WIKIBOT_PASSWORD}
      - WIKI_CATEGORY=${WIKI_CATEGORY}
